apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount-controller.yaml
  - serviceaccount-runner.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole-runner.yaml
  - clusterrolebinding-runner.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: devbox-agent
    includeSelectors: true

configMapGenerator:
  - name: devbox-agent-config
    files:
      - config.yaml
    options:
      disableNameSuffixHash: false
